image: jangrewe/gitlab-ci-android

before_script:
	-export GRADLE_USER_HOME=$(pwd)/.gradle
	-export BUILD_NUMBER=$(git rev-list --count ${CI_BUILD_REF})
	-export BUILD_COMMIT_SHA=${CI_COMMIT_SHA}

stages:
	-build

buildDebug:
	stage: build
	script:
		-./gradlew clean assebleDebug
	retry: 2
	artifacts:
		name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${BUILD_NUMBER}"
		paths:
			-app/build/outputs/
	only:
		-master